### PR TITLE
Added mazeview for yate.

### PR DESCRIPTION
**Pull request by reald**

### CODE REVIEW

**Review by bef — COMMENTED** [review]
Thank you for contributing.
May I ask why ygi is loaded, which is not a dependency for mazeview?

**Comment by reald** [comment]
I copied it from mazegame-yate.tcl . But it is not necessary here so I removed it now.

**Comment by bef** [comment]
Hello there. Your script looks very similar to the already existing mazeview.tcl, which does not depend on either asterisk or yate. Is there any particular reason to have another copy of the same script?

**Comment by reald** [comment]
No there isn´t. Had some problems with it in the past but your version is working now. PR can be closed.

**Pull request closed without merging**
